# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'AutomationEngineerLab (159ab5c4-90b4-42a3-aeb4-199816bf79ed)'
    backendAzureRmSubscriptionId: '159ab5c4-90b4-42a3-aeb4-199816bf79ed'
    backendAzureRmResourceGroupName: 'tfstate'
    backendAzureRmStorageAccountName: 'tfstate662'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'AutomationEngineerLab (159ab5c4-90b4-42a3-aeb4-199816bf79ed)'
    providerAzureRmSubscriptionId: '159ab5c4-90b4-42a3-aeb4-199816bf79ed'
    allowTelemetryCollection: true
    publishPlanResults: 'tf.tfplan'